baseURL: "http://1shubham7.netlify.app/"
title: Shubham Singh
paginate: 5
theme: PaperMod
languageCode: en-us

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:

  #theme
  showtoc: true
  tocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hidemeta: false

  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  # Introduction

  profile-mode:
    enabled: true
    title: "Shubham Singh"
    subtitle: Hi there 👋! This is Shubham from India. I am First year undergrad (Computer Science Engineering) from a tier-3 college, I am an open-source enthusiast. I am a web developer, Android developer, and right now I am learning DevOps. When not coding, you will find me reading books and listening podcasts around history, geopolitics, tech and entrepreneurship.
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    imageAlt: "Shubham Singh"
    buttons:
       - name: "Follow me on Twitter"
         url: "https://twitter.com/1shubham7"

  # List view
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hideSummary: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    iconHeight: 35


  # home-info mode
  homeInfoParams:
    Title: "Hi there, This is Shubham Singh from India. \U0001F44B"
    Content: I am an open-source enthusiast, Web developer, Andriod developer, first year undergrad (Computer Science Engg.). I also have decent knowledge of DevOps and I wish to learn it further. I am applying for LFX Mentorship (Term-2) under the CNCF Notary Project. I have made this website in Hugo in order to show my passion for LFX and the Notary Project.

  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/shubham-singh-mahar-5a002b20b/"
    - name: Hashnode
      url: "https://1shubham7.hashnode.dev/"
    - name: Github
      url: "https://github.com/1shubham7"
    - name: Twitter
      url: "https://twitter/1shubham7"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Me
      name: Me
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: GitHub
      name: github.com
      url: https://github.com/1shubham7
      weight: 60
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai