baseURL: "http://1shubham7.netlify.app/"
title: Shubham Singh
theme: PaperMod
languageCode: en-us

googleAnalytics: UA-123-45

params:

  #theme
  showtoc: true
  tocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hidemeta: false

  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  # Introduction

  profileMode:
    enabled: true
    title: "Shubham Singh"
    subtitle: Hi there 👋! This is Shubham. I am First year undergrad (Computer Science Engineering), I am an open-source enthusiast. I am a web developer, Android developer, and right now I am learning DevOps. When not coding, you will find me reading books and listening podcasts around history, geopolitics, tech and entrepreneurship.
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    imageAlt: "Shubham Singh"
    buttons:
      - name: "Follow me on Twitter"
        url: "https://twitter.com/1shubham7"

  # List view
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  # UseHugoToc: true
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  # comments: true
  # hideSummary: false


  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/shubham-singh-mahar-5a002b20b/"
    - name: Hashnode
      url: "https://1shubham7.hashnode.dev/"
    - name: Github
      url: "https://github.com/1shubham7"
    - name: Twitter
      url: "https://twitter/1shubham7"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: Me
      name: Me
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: GitHub
      name: github.com
      url: https://github.com/1shubham7
      weight: 60
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai